Feature/number rules and constraints
j3-fortran/generics pull request #141
Opened 2024-09-30 19:55 UTC by tclune

2024-09-30 21:23 UTC, aury6623 requested changes

2024-09-30 21:23 UTC, aury6623 commented on J3-Papers/edits/templates.txt
> +C2028 (R????). An entity declared by <type-declaration-stmt> shall have
```suggestion
C2028 (R2015). An entity declared by <type-declaration-stmt> shall have
```

2024-09-30 21:23 UTC, aury6623 commented on J3-Papers/edits/instantiation.txt
> +R2039 <instantiation-arg-spec> <<is>>
R2038 was skipped. Accounting for this skip and the +10 skip from before, this should be R2028.

2024-10-01 13:39 UTC, tclune commented on J3-Papers/edits/concepts.txt
>              <explicit-bounds-expr> shall not appear as a lower bound.
Q:  Can a constraint reference multiple rules?    I saw in some of the "co-array" [sic] edits papers some examples like that.  Did not search in the actual standard though.

2024-10-01 13:41 UTC, tclune commented on J3-Papers/edits/instantiation.txt
> +R2034 <template-instantiate-stmt>
Yes - that would have been better.   I'm leaving this one unresolved so that I remember to propagate.

2024-10-01 15:01 UTC, aury6623 commented on J3-Papers/edits/concepts.txt
>              <explicit-bounds-expr> shall not appear as a lower bound.
I searched the standard for `, R` which would find things like `(R1234, R1235)` but it didn't find that on any constraints (my PDF tool doesn't support regex searches, sadly!) I also just scrolled around for a bit and didn't see any. So I think the answer is no.

2024-10-01 16:43 UTC, tclune commented on J3-Papers/edits/instantiation.txt
> +R2034 <template-instantiate-stmt>
Am fixing manually in my sandbox.

2024-10-01 16:54 UTC, tclune commented on J3-Papers/edits/misc-edits.txt
> +  Constraint(R508): <template> or <requirement> shall only appear in a
Agreed.   I've made the change (in sandbox), and added a UTI.

2024-10-01 21:51 UTC, aury6623 commented on J3-Papers/edits/concepts.txt
>              <explicit-bounds-expr> shall not appear as a lower bound.
@tclune Why is this marked resolved? It has not been addressed. Can you unmark it?

2024-10-02 12:48 UTC, tclune commented on J3-Papers/edits/concepts.txt
>              <explicit-bounds-expr> shall not appear as a lower bound.
Apologies - I must have clicked on the wrong "close" on accident.

2024-10-02 12:49 UTC, tclune commented on J3-Papers/edits/concepts.txt
>              <explicit-bounds-expr> shall not appear as a lower bound.
Should they possibly be moved up in the text as well?

2024-10-07 17:37 UTC, aury6623 approved these changes

2024-10-07 17:37 UTC, merged