Update papers in response to comments from Oct 24 J3 meeting
j3-fortran/generics pull request #146
Opened 2024-10-24 06:09 UTC by aury6623

**I suggest reviewing each commit separately. All together they will be a mess.**

I am not done yet, but I think these edits should be pretty agreeable. I added some UTIs, mostly around notes that need to be fixed. I also found one case of ambiguous syntax that we need to address. I will keep working while this is reviewed. I will next attempt to address the issue of misuse of BNF terms vs semantic terms, especially in regards to `<deferred-arg>` and some of the constraints relating to it.

@tclune @everythingfunctional 

- Change clause 20 to clause 15. Maybe we can do 14.4 later, but I don't think it should be in 14
- Consistent headers
- Reformat notes and add UTIs
- Remove unnecessary dot after constraints
- Change constraints and bnf rules to C15 and R15
- Address misc comments from today's meeting
- Rename papers to remove revision number, change revision number to rX in To: line

2024-10-24 15:44 UTC, aury6623 commented
Added one more commit with some updates from Malcolm's notes which Tom forwarded to me this morning.

2024-10-24 16:29 UTC, aury6623 commented
Added one more commit to delete a useless constraint.

2024-10-24 16:38 UTC, tclune requested changes
Unfortunately, because of the filename changes, GitHub is showing this as "all changed" making a review impossible.

Not sure what to suggest aside from doing the name change separately.

2024-10-24 16:39 UTC, aury6623 commented
> Unfortunately, because of the filename changes, GitHub is showing this as "all changed" making a review impossible.
> 
> Not sure what to suggest aside from doing the name change separately.

Please read the PR description.

If you review each commit individually, this is not an issue.

2024-10-24 19:03 UTC, tclune commented on J3-Papers/edits/24-161r2_concepts.txt
> +15.2.1.1 General
Malcolm wanted one less level of nesting here.

2024-10-24 19:04 UTC, tclune approved these changes

2024-10-24 19:05 UTC, tclune commented on J3-Papers/edits/24-161r2_concepts.txt
> +NOTE
Needs number.

2024-10-24 19:05 UTC, tclune commented on J3-Papers/edits/24-161r2_concepts.txt
> +NOTE
Is the note going away as per later comments?

2024-10-24 19:06 UTC, aury6623 commented on J3-Papers/edits/24-161r2_concepts.txt
> +15.2.1.1 General
Please read the PR description.

> Also I tried to fix the issue of too-deep nesting, but it was tricky without moving stuff around too much. I think we should do that at the same time as we reorganize the paper into a monolithic paper and shuffle around the subclauses.

2024-10-24 19:06 UTC, aury6623 commented on J3-Papers/edits/24-161r2_concepts.txt
> +NOTE
Notes that appear alone in their subclause are not numbered.

2024-10-24 19:06 UTC, tclune commented on J3-Papers/edits/24-161r2_concepts.txt
> +NOTE 1
Do the NOTE numbers start over with each subclause?

2024-10-24 19:06 UTC, aury6623 commented on J3-Papers/edits/24-161r2_concepts.txt
> +NOTE 1
Yes.

2024-10-24 19:10 UTC, tclune commented on J3-Papers/edits/24-161r2_concepts.txt
> +    A deferred type is cannot be extended. The name of the EXTENSIBLE
Isn't "cannot" still too "normative"?

2024-10-24 19:11 UTC, tclune commented on J3-Papers/edits/24-161r2_concepts.txt
> +C1514 (R1509) Each <deferred-proc-name> shall appear in the the
Duplicate "the the".   But GitHub won't let me make a "suggestion" to fix.

2024-10-24 19:12 UTC, tclune commented on J3-Papers/edits/24-161_concepts.txt
> +To: J3                                                     J3/24-161rX
I think this will break the upload mechanism.   (But I need to check, so just a cautionary note before we merge.)

2024-10-24 19:14 UTC, tclune commented on J3-Papers/edits/24-161_concepts.txt
> +To: J3                                                     J3/24-161rX
ok - always remember this incorrectly.

2024-10-24 19:14 UTC, tclune commented
Starting a list of other issues that came up but have not been addressed yet:

*  "TYPE, DEFERRED" --> "DEFERRED TYPE"
*  ???

2024-10-24 19:20 UTC, aury6623 commented on J3-Papers/edits/24-161r2_concepts.txt
> +    A deferred type is cannot be extended. The name of the EXTENSIBLE
I found multiple existing notes in the standard that say "cannot". But also some normative text says "cannot" too.

There is a typo here "is cannot". Also I'm not sure this note is final anyway, with the "primarily refers" wording. It's better than before though.

2024-10-24 19:20 UTC, tclune commented
> Please read the PR description. Specifically the very first line of the description, which is in bold.
> 
> If you review each commit individually, this is not an issue.

Yeah - I was about to try that earlier before I was sidetracked by the day job.   I've given my initial pass at the changes - very nice.

I will wait to merge until we've resolved a few issues to minimize the amount of upload/download that otherwise ensues.

2024-10-24 19:21 UTC, aury6623 commented on J3-Papers/edits/24-161_concepts.txt
> +To: J3                                                     J3/24-161rX
We can change it again before uploading, if it does. I just want to make it clear that this revision is not an uploaded paper. I think we can keep the file names permanently unrevisioned, so we don't have to keep renaming them. At least until they make it to "25-" .

2024-10-24 20:07 UTC, aury6623 commented
I am ready for this PR to be merged, if you are. I'm not sure if we're waiting for @everythingfunctional .
Again, after merging I recommend **not** updating the J3 papers yet.

2024-10-27 21:39 UTC, tclune commented
I'm merging now.

My real conundrum is, what papers should I be telling plenary to discuss?    Need to announce that before our subgroup meeting.

2024-10-27 21:39 UTC, merged