Updates based upon this weeks generics telecon.
j3-fortran/generics pull request #51
Opened 2022-01-12 23:22 UTC by tclune

2022-01-13 01:59 UTC, everythingfunctional commented on J3-Papers/Generics_Requirements.txt
> +        END TEMPLATE
Plus didn't actually get used in this example. Not exactly sure how it would be in this case, but perhaps worth some thought.

2022-01-13 02:00 UTC, everythingfunctional commented on J3-Papers/Generics_Requirements.txt
> +     Note 2: A generic operator may be passed as a dummy argument, because resolution cane
```suggestion
     Note 2: A generic operator may be passed as a dummy argument, because resolution can
```

2022-01-13 13:22 UTC, tclune commented on J3-Papers/Generics_Requirements.txt
> +        END TEMPLATE
Yes - wanted to do another sweep on the examples.  But ran out of time.  Please go ahead and get this approved so that those that can't/won't use GitHub have a valid link for the update.

2022-01-13 19:26 UTC, everythingfunctional approved these changes

2022-01-13 19:27 UTC, everythingfunctional commented on J3-Papers/Generics_Requirements.txt
> +        END TEMPLATE
Approved, not sure why it wont let me merge though.

2022-01-14 16:02 UTC, rouson requested changes
I suggested on grammar correction and and made two comments that might require additional material to address.

2022-01-14 16:02 UTC, rouson commented on J3-Papers/Generics_Requirements.txt
>     type-bound operators/procedures if necessary.
It might be helpful to explain the reasons disallowing type-bound procedures. Is the problem related to runtime polymorphism and the inability to ensure type safety for polymorphic arguments?   On a related note, can type-spec template parameters be polymorphic?

2022-01-14 16:50 UTC, tclune commented
Can we please get the PR into the text first. And then open new PRs for the individual elements?

2022-01-14 17:19 UTC, tclune commented
Changed permissions so that I can force through PRs.

2022-01-14 17:19 UTC, merged